#!/usr/bin/env python3

from esipy import ESI
import argparse
import os

def main():
    # First we define each parser
    parser = argparse.ArgumentParser()
    parser.add_argument('name', default='.', help='Name (without extension) of the AOMs')
    parser.add_argument('-r', '--rings', nargs='+', help='Rings. For more than one ring, separate using a colon (e.g., "-r 1 2 3 4 5 6, 7 8 9 10 11 12")')
    parser.add_argument('-mci', action='store_true', help='Whether to compute the MCI')
    parser.add_argument('-av1245', action='store_true', help='Whether to compute the AV1245')
    parser.add_argument('-n', '--ncores', default=1, type=int, help='Number of cores for the MCI')
    parser.add_argument('-v', '--verbose', action='store_true', help='Verbose')

    args = parser.parse_args()

    if not args.rings:
        parser.error("No rings specified. You must specify at least one ring.")

    rings = []
    current_group = []
    for item in args.rings:
        parts = item.split(',')
        for i, part in enumerate(parts):
            if part.strip():  # if part is not empty
                try:
                    current_group.append(int(part))
                except ValueError:
                    parser.error(f"Invalid ring number: {part}")
            # If there was a comma, we end the current group
            if i < len(parts) - 1:
                rings.append(current_group)
                current_group = []

    if current_group:
        rings.append(current_group)

    if not rings:
        parser.error("No rings specified. You must specify at least one ring.")

    path = args.name
    if not os.path.isdir(path):
        parser.error(f"Error: The path '{path}' does not exist or is not a directory.")

    # Assigning argument values to variables
    mci = True if args.mci else None
    av1245 = True if args.av1245 else None
    ncores = args.ncores

    # Printing the verbose if specified
    if args.verbose:
        print(" Verbose Mode Enabled:")
        print(f" Path: {args.path}")
        for i, ring in enumerate(rings, 1):
            print(f" Ring {i}: {ring}")
        print(f" MCI: {mci}")
        print(f" AV1245: {av1245}")
        print(f" Number of Cores: {ncores}")

    part = path.split('_')[-1]
    aom_file = path + ".aoms"
    molinfo_file = path + ".molinfo"
    if args.verbose:
        print(f"Processing file: {aom_file}")

    arom = ESI(aom=aom_file, molinfo=molinfo_file, readpath=path, rings=rings, partition=part, ncores=ncores, mci=mci, av1245=av1245)
    arom.print()

if __name__ == '__main__':
    main()
