#!/usr/bin/env python3

from esipy import ESI
from esipy.readfchk2 import readfchk
import argparse
import os

def main():
    # First we define each parser
    parser = argparse.ArgumentParser()
    parser.add_argument('fchname', help='Name of the .fchk file')
    parser.add_argument('-r', '--rings', nargs='+',
                        help='Rings. For more than one ring, separate using a comma (e.g., "-r 1 2 3 4 5 6, 7 8 9 10 11 12")')
    parser.add_argument('-p', '--partition', type=str, help='Partition')
    parser.add_argument('-mci', action='store_true', help='Whether to compute the MCI')
    parser.add_argument('-av1245', action='store_true', help='Whether to compute the AV1245')
    parser.add_argument('-n', '--ncores', default=1, type=int, help='Number of cores for the MCI')
    parser.add_argument('-s', '--save', action='store_true', help='Whether to save the AOMs (and molinfo if specified)')
    parser.add_argument('-v', '--verbose', action='store_true', help='Verbose')
    parser.add_argument('-w', '--write-aoms', action='store_true', help='Whether to write the AOMs in AIMAll format')

    args = parser.parse_args()

    if not args.rings:
        parser.error("No rings specified. You must specify at least one ring.")

    rings = []
    current_ring = []
    for item in args.rings:
        parts = item.split(',')
        for i, part in enumerate(parts):
            if part.strip():  # if part is not empty
                try:
                    current_ring.append(int(part))
                except ValueError:
                    parser.error(f"Invalid ring number: {part}")
            # If there was a comma, we end the current group
            if i < len(parts) - 1:
                rings.append(current_ring)
                current_ring = []

    if current_ring:
        rings.append(current_ring)

    if not rings:
        parser.error("No rings specified. You must specify at least one ring.")

    # Assigning argument values to variables
    fchname = args.fchname
    mci = args.mci
    av1245 = args.av1245
    ncores = args.ncores
    save = args.save
    writeaoms = args.write_aoms

    if args.partition is None:
        print(" | No partition specified. Using only robust schemes meta-Lowdin, NAO and IAO")
        partition = ['meta_lowdin', 'nao', 'iao']
    elif args.partition == "all" or args.partition == "a":
        partition = ["mulliken", "lowdin", "meta_lowdin", "nao", "iao"]
    elif args.partition == "robust" or args.partition == "r":
        partition = ['meta_lowdin', 'nao', 'iao']
    else:
        parts = args.partition.split(',')
        partition = []
        for part in parts:
            partition.append(part)

    # Checking if the file exists
    if not os.path.isfile(fchname):
        parser.error(f"Error: The file '{fchname}' does not exist.")
        exit(1)

    # Printing the verbose if specified
    if args.verbose:
        print(" Verbose Mode Enabled:")
        print(f" fchname: {args.fchname}")
        print(f" Number of Rings (--num-rings): {args.num_rings}")
        for i, ring in enumerate(rings, 1):
            print(f" Ring {i}: {ring}")
        print(f" Partition(s): {partition}")
        print(f" MCI: {mci}")
        print(f" AV1245: {av1245}")
        print(f" Number of Cores: {ncores}")
        print(f" Write molinfo file(s): {molinfo}")
        print(f" Save file(s): {save}")

    molname, filename = os.path.splitext(fchname)

    mol, mf = readfchk(molname + filename)

    os.chdir(os.getcwd())
    for part in partition:
        save_name = molname + '_' + part
        print(f' Saving the AOMs in the file: {save_name}.aoms')
        arom = ESI(mol=mol, mf=mf, rings=rings, partition=part, save=save_name)
        arom.print()
        if writeaoms:
            arom.writeaoms()

if __name__ == '__main__':
    main()