#!/usr/bin/env python3

import esipy
import argparse
import os

def main():
    # First we define each parser
    parser = argparse.ArgumentParser()
    parser.add_argument('fchname', help='Name of the .fchk file')
    parser.add_argument('-nr', '--num-rings', type=int, default=1, help='Number of rings')
    parser.add_argument('-p', '--partition', type=str, help='Partition')
    parser.add_argument('-mci', action='store_true', help='Whether to compute the MCI')
    parser.add_argument('-av1245', action='store_true', help='Whether to compute the AV1245')
    parser.add_argument('-n', '--ncores', default=1, type=int, help='Number of cores for the MCI')
    parser.add_argument('-s', '--save', action='store_true', help='Whether to save the AOMs (and molinfo if specified)')
    parser.add_argument('-v', '--verbose', action='store_true', help='Verbose')
    parser.add_argument('-w', '--write-aoms', action='store_true', help='Whether to write the AOMs in AIMAll format')

    #args = parser.parse_args()
    args, unknown = parser.parse_known_args()

    for i in range(1, args.num_rings + 1):
        parser.add_argument(f'-r{i}', f'--ring{i}', type=int, nargs='+', help=f'Ring {i}')

    args = parser.parse_args()

    rings = []
    for i in range(1, args.num_rings + 1):
        ring_attr = getattr(args, f'ring{i}', None)
        if ring_attr:
            rings.append(ring_attr)

    # Checking if a ring is provided
    if not rings:
        parser.error(f"No ring specified. You must specify at least one ring.")

    # Assigning argument values to variables
    fchname = args.fchname
    mci = args.mci
    av1245 = args.av1245
    num_threads = args.ncores
    save = args.save

    # Checking if the file exists
    if not os.path.isfile(fchname):
        parser.error(f"Error: The file '{fchname}' does not exist.")
        exit(1)

    # Printing the verbose if specified
    if args.verbose:
        print(" Verbose Mode Enabled:")
        print(f" fchname: {args.fchname}")
        print(f" Number of Rings (--num-rings): {args.num_rings}")
        for i, ring in enumerate(rings, 1):
            print(f" Ring {i}: {ring}")
        print(f" Partition(s): {partition}")
        print(f" MCI: {mci}")
        print(f" AV1245: {av1245}")
        print(f" Number of Threads: {num_threads}")
        print(f" Write molinfo file(s): {molinfo}")
        print(f" Save file(s): {save}")

    molname, filename = os.path.splitext(fchname)

    mol, mf = esipy.readfchk.readfchk(molname + filename)
    print(mol)
    print(mf)

    os.chdir(os.getcwd())
    for part in partition:
        save_name = molname + '_' + part
        print(f' Saving the AOMs in the file: {save_name}.aoms')
        arom = esipy.ESI(mol=mol, mf=mf, rings=rings, partition=part, saveaoms=save_name + '.aoms', savemolinfo=save_name + '.molinfo')
        arom.print()
        if args.writeaoms:
            arom.writeaoms()
if __name__ == '__main__':
    main()