#!/usr/bin/env python3

from esipy import ESI
import argparse
import os

def main():
    # Define the argument parser
    parser = argparse.ArgumentParser()
    parser.add_argument('name', default='.', help='Name (without extension) of the INTs')
    parser.add_argument('-v', '--verbose', action='store_true', help='Verbose')

    args = parser.parse_args()

    # Construct the full path based on the script's directory
    path = os.path.join(os.getcwd(), args.name)
    if not os.path.isdir(path):
        parser.error(f"Error: The path '{path}' does not exist or is not a directory.")

    # Assigning argument values to variables
    verbose = args.verbose

    # Printing the verbose if specified
    if verbose:
        print(" Verbose Mode Enabled:")
        print(f" Path: {path}")

    int_file = os.path.join(path, args.name + ".ints")
    molinfo_file = os.path.join(path, args.name + ".molinfo")
    if verbose:
        print(f"Processing file: {int_file}")

    # Initialize ESI and process the files
    arom = ESI(ints=int_file, molinfo=molinfo_file, readpath=path)
    arom.print()

if __name__ == '__main__':
    main()
